#!/bin/bash

if [ "$#" -eq 3 ]; then 
	if [ $1 = "local-eclipse" ]; then # local through Eclipse
		ServiceURL="http://localhost:8080/eexcess-privacy-proxy/" 
	else 
		if [ $1 = "local" ]; then # local manual deployment
			ServiceURL="http://localhost:8080/eexcess-privacy-proxy-1.0-SNAPSHOT/"
		else 
			if [ $1 = "remote-dev" ]; then # development server
				ServiceURL="http://eexcess-dev.joanneum.at/eexcess-privacy-proxy-1.0-SNAPSHOT/"
			else 
				ServiceURL=$1 # specific location
			fi
		fi
	fi
	File=$2
	Method=$3
	ServiceURL=`echo $ServiceURL"api/v1/getDetails"`
	curl -X $Method $ServiceURL -d @$File --header "Content-Type: application/json"
else 
	echo "Usage 'getDetails local-eclipse|local|remote-dev|<http://your-server/api/> input-test-file.json POST|OPTIONS'"
fi
